spring:
  application:
    name: service-order
  profiles:
    active: dev
    # 包含 application-feign.yml, application-sentinel.yml
    include: feign,sentinel
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        namespace: 54725212-72d0-4b26-afe5-00ba1ac4712c
        group: order

server:
  port: 8000

logging:
  level:
    root: info
    me.cowra.demo: debug

---
spring:
  config:
    import:
      - nacos:commons.yml
      - nacos:database.yml
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:commons.yml
      - nacos:database.yml
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:commons.yml
      - nacos:database.yml
    activate:
      on-profile: prod