spring:
  application:
    name: service-product
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        import-check:
          enabled: false
        group: product

server:
  port: 9000

logging:
  level:
    root: info
    me.cowra.demo: debug